# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: KnowledgeBase
topnav_title: KnowledgeBase
site_title: KnowledgeBase

#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My personal KnowledgeBase
baseurl: "/knowledge" # the subpath of your site, e.g. /blog
url: "https://thamielis.github.io/knowledge" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  thamielis

output: web


# Build settings
# theme options from https://bootswatch.com/3/
# comment out this to use default Bootstrap
bootwatch: paper # cerulean cosmo custom cyborg darkly flatly journal lumen readable sandstone simplex slate solar spacelab superhero united yeti

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

highlighter: rouge
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

timezone: Europe/Vienna

defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"
    search: true
    sidebar: knowledge_sidebar
    topnav: topnav

- scope:
    path: powershell
    type: md
  values:
    layout: docs
    sectionid: powershell
    search: true
    sidebar: powershell_sidebar
    topnav: topnav

- scope:
    path: pages
    type: pages
  values:
    layout: page
    comments: false
    # if you don't want to use Commento.io and just hide comments, change true to false wherever you see the comments property
    search: true
    sidebar: home_sidebar
    topnav: topnav
  
- scope:
    path: ""
    type: tooltips
  values:
    layout: page
    search: true
    tooltip: true

collections:
  tooltips:
    output: false
  docs:
    permalink: /:collection/:path
    output: true
  md:
    permalink: /:collection/:path
    output: true
  #posts:
  #  permalink: /blog/:year/:month/:day/:title/
  #  output: true

sidebars:
- home_sidebar
- knowledge_sidebar
- powershell_sidebar

github: [metadata]

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
